add configs\templates

diff --git a/.github/workflows/padavan-ci.yml b/.github/workflows/padavan-ci.yml
--- a/.github/workflows/padavan-ci.yml
+++ b/.github/workflows/padavan-ci.yml
@@ -51,16 +51,21 @@ jobs:
 
     - name: Edit .config
       run: |
-        cp -f diy.sh /opt/rt-n56u/trunk/configs/templates/
-        cd /opt/rt-n56u/trunk/configs/templates/
-        if [ ! -f $TNAME.config ] ; then
+        #cp -f diy.sh /opt/rt-n56u/trunk/configs/templates/
+        #cd /opt/rt-n56u/trunk/configs/templates/
+        #if [ ! -f $TNAME.config ] ; then
+        #echo "$TNAME.config not found "
+        #exit 1
+        #fi
+        #cp -f $TNAME.config .config
+        #chmod +x diy.sh
+        #sh diy.sh
+        #mv -f .config $TNAME.config
+        if [ ! -f configs/templates/$TNAME.config ] ; then
         echo "$TNAME.config not found "
         exit 1
         fi
-        cp -f $TNAME.config .config
-        chmod +x diy.sh
-        sh diy.sh
-        mv -f .config $TNAME.config
+        cp -f configs/templates/$TNAME.config /opt/rt-n56u/trunk/$TNAME.config
 
     - name: Build Firmware
       run: |
